springdoc:
  api-docs:
    path: /openapi
server:
  port: 3000
spring:
  artemis:
    mode: embedded
    embedded:
      persistent: false
      enabled: true
  jta:
    enabled: true
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;AUTOCOMMIT=OFF
    username: sa
    password: password
    driverClassName: org.h2.Driver
  # datasource:
  #  url: jdbc:postgresql://localhost:5432/postgres
  #  username: postgres
  #  password: xxxxxxxx
  jpa:
    properties:
      jakarta:
        persistence:
          transactionType: JTA
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.AtomikosJtaPlatform
    hibernate:
      ddl-auto: update
  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:static/
  web:
    resources:
      cache:
        period: 0
